### ISSUE TITLE
Compiling on Old Environments

### ISSUE THREAD

**Issue by josiahseaman** [josiahseaman/DDV#88]
This issue is here to catch people trying to install on an old environment.  The solution is to simply upgrade pip and setuptools:
```
pip install --upgrade pip
pip install --upgrade setuptools
```
See [Installation Instructions](https://github.com/josiahseaman/FluentDNA/blob/python-master/docs/installation.md) for more details.

The error looks like:
```
(oldEnv)josiah@newline-production:~$ pip install --upgrade git+https://github.com/josiahseaman/FluentDNA.git@i86_repeatmasker_gallery
You are using pip version 7.1.0, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/josiahseaman/FluentDNA.git@i86_repeatmasker_gallery
  Cloning https://github.com/josiahseaman/FluentDNA.git (to i86_repeatmasker_gallery) to /tmp/pip-vt38cdya-build
Collecting pip>=18.0 (from DDV==2.4.5)
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Collecting setuptools>=41.5 (from DDV==2.4.5)
  Using cached https://files.pythonhosted.org/packages/ea/98/9db5ebb9c33716ab8c45ee355a300facb44575b9b6d68a95fa49e81a2f04/setuptools-41.5.0-py2.py3-none-any.whl
Collecting Pillow>=3.2.0 (from DDV==2.4.5)
  Using cached https://files.pythonhosted.org/packages/5b/bb/cdc8086db1f15d0664dd22a62c69613cdc00f1dd430b5b19df1bea83f2a3/Pillow-6.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/Pillow.egg-info
    writing pip-egg-info/Pillow.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/Pillow.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/Pillow.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/Pillow.egg-info/SOURCES.txt'
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    warning: manifest_maker: standard file '-c' not found

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-xiy1efcl/Pillow/setup.py", line 888, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "/home/josiah/oldEnv/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 207, in find_sources
        mm.run()
      File "/home/josiah/oldEnv/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 291, in run
        self.add_defaults()
      File "/home/josiah/oldEnv/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 320, in add_defaults
        sdist.add_defaults(self)
      File "/home/josiah/oldEnv/lib/python3.4/site-packages/setuptools/command/sdist.py", line 130, in add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-xiy1efcl/Pillow/setup.py", line 335, in finalize_options
        if sys.version_info.major >= 3 and not self.parallel:
      File "/usr/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: parallel

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xiy1efcl/Pillow
```

**Comment by josiahseaman** [comment]
If you get a ModuleNotFoundError or ImportError when using the Executable binary, try placing all the files currently in the lib directory into the parent directory beside the .EXE.  I've tried to clean up the executable directory by moving some files into /lib/ and testing to see if this causes a crash.  It's unnecessary, I'm just trying to create a cleaner work environment.
